### ISSUE TITLE
I can't call progress or sth like it!?

### ISSUE THREAD

**Issue by omidmohebbise** [vashisthg/StartPointSeekBar#7]
Hello
I need to read position from httpConnection and set it on StartPointSeekBar.
How to change its position?
thank you for all you do.

**Comment by vashisthg** [comment]
@omidmohebbise Thanks for the suggestion. Adding the functionality.

**Comment by vashisthg** [comment]
@omidmohebbise Please check the PR #8 , checkout branch ```setProgress``` and tell me if it works for your issue.

**Comment by danem** [comment]
I too would like this functionality, and the new commit seems to fit my needs fine.

**Comment by omidmohebbise** [comment]
Thank you so much
It work prosaically  😁

**Comment by vashisthg** [comment]
Closing this.
